env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: latest
rules: {}
root: true
ignorePatterns:
  - "plugins/*"
  - "template/*"
